import { jsPDF } from 'jspdf';

// Generate and download a PDF report for a diagnosis.
export function exportDiagnosisPdf(diagnosis) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  // Helper: add text with word-wrap
  const addWrapped = (text, fontSize, opts = {}) => {
    doc.setFontSize(fontSize);
    if (opts.bold) doc.setFont('helvetica', 'bold');
    else doc.setFont('helvetica', 'normal');
    if (opts.color) doc.setTextColor(...opts.color);
    else doc.setTextColor(30, 30, 30);

    const lines = doc.splitTextToSize(text, contentW);
    const lineH = fontSize * 0.5;

    // Check if we need a new page
    if (y + lines.length * lineH > 270) {
      doc.addPage();
      y = margin;
    }

    doc.text(lines, margin, y);
    y += lines.length * lineH + 2;
  };

  //Header bar
  doc.setFillColor(27, 54, 33); // brand-secondary
  doc.rect(0, 0, pageW, 40, 'F');

  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('PLANTAECH', margin, 18);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(200, 220, 200);
  doc.text('Tomato Leaf Disease Diagnosis Report', margin, 28);

  const dateStr = diagnosis.created_at
    ? new Date(diagnosis.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    : new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  doc.text(dateStr, pageW - margin, 28, { align: 'right' });

  y = 52;

  // Diagnosis summary
  addWrapped('DIAGNOSIS SUMMARY', 14, { bold: true, color: [27, 54, 33] });
  y += 2;

  // Disease name
  addWrapped(`Disease: ${diagnosis.disease_name || 'Unknown'}`, 12, { bold: true });
  if (diagnosis.scientific_name) {
    addWrapped(`Scientific Name: ${diagnosis.scientific_name}`, 10, { color: [100, 100, 100] });
  }

  // Confidence & severity
  const conf = diagnosis.confidence != null ? `${diagnosis.confidence.toFixed(1)}%` : 'N/A';
  const sev = diagnosis.severity
    ? diagnosis.severity.charAt(0).toUpperCase() + diagnosis.severity.slice(1)
    : 'Not applicable';
  addWrapped(`Confidence: ${conf}`, 11);
  addWrapped(`Severity: ${sev}`, 11);

  y += 4;

  // Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // Immediate Action
  if (diagnosis.immediate_action) {
    addWrapped('IMMEDIATE ACTION', 12, { bold: true, color: [180, 100, 0] });
    y += 1;
    addWrapped(diagnosis.immediate_action, 10);
    y += 4;
  }

  // Treatment Plan
  if (diagnosis.treatment_plan) {
    addWrapped('TREATMENT PLAN', 12, { bold: true, color: [30, 100, 160] });
    y += 1;
    addWrapped(diagnosis.treatment_plan, 10);
    y += 4;
  }

  // Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // Metadata
  addWrapped('ANALYSIS METADATA', 11, { bold: true, color: [100, 100, 100] });
  y += 1;

  const meta = diagnosis.metadata || {};
  if (meta.model_version) addWrapped(`Model Version: ${meta.model_version}`, 9, { color: [120, 120, 120] });
  if (meta.analyzed_at) addWrapped(`Analyzed At: ${new Date(meta.analyzed_at).toLocaleString()}`, 9, { color: [120, 120, 120] });

  // Top-K predictions
  if (meta.top_k && meta.top_k.length > 0) {
    y += 2;
    addWrapped('Top Predictions:', 9, { bold: true, color: [120, 120, 120] });
    meta.top_k.forEach((pred, i) => {
      const name = pred.class_name || 'Unknown';
      const pconf = (pred.confidence * 100).toFixed(1);
      addWrapped(`  ${i + 1}. ${name} — ${pconf}%`, 9, { color: [120, 120, 120] });
    });
  }

  // Footer
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text('Generated by Plantaech — plantaech.vercel.app', margin, pageH - 10);
  doc.text(`Report ID: ${diagnosis.id || 'N/A'}`, pageW - margin, pageH - 10, { align: 'right' });

  // Save
  const shortId = (diagnosis.id || 'report').slice(0, 8);
  doc.save(`plantaech-diagnosis-${shortId}.pdf`);
}
